language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules
script:
  - yarn build
  - npm install -g now
  - yarn copy_now

deploy:
  provider: script
  script: now --no-clipboard --token=$NOW_TOKEN --build-env REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY  --build-env REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID && now alias
  local_dir: build
  on:
    branch: master

